// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrVvx3DcWcX561wOXmmHJqcgAxPs04mbc',
    appId: '1:998880249029:web:6ff1ae5d88e9a01b695cac',
    messagingSenderId: '998880249029',
    projectId: 'findora-474614',
    authDomain: 'findora-474614.firebaseapp.com',
    storageBucket: 'findora-474614.firebasestorage.app',
    measurementId: 'G-9CHHNWFVVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-cVV4EkDATZWhW8ygDu2ZY-F4P8S_U3E',
    appId: '1:998880249029:android:a638a76dad5c9604695cac',
    messagingSenderId: '998880249029',
    projectId: 'findora-474614',
    storageBucket: 'findora-474614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW5WJB0N30syoal2w0yva3Nw9bISutHng',
    appId: '1:998880249029:ios:fc133fc106295ecd695cac',
    messagingSenderId: '998880249029',
    projectId: 'findora-474614',
    storageBucket: 'findora-474614.firebasestorage.app',
    iosBundleId: 'com.latihan.pam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW5WJB0N30syoal2w0yva3Nw9bISutHng',
    appId: '1:998880249029:ios:fc133fc106295ecd695cac',
    messagingSenderId: '998880249029',
    projectId: 'findora-474614',
    storageBucket: 'findora-474614.firebasestorage.app',
    iosBundleId: 'com.latihan.pam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrVvx3DcWcX561wOXmmHJqcgAxPs04mbc',
    appId: '1:998880249029:web:54e27c4346036616695cac',
    messagingSenderId: '998880249029',
    projectId: 'findora-474614',
    authDomain: 'findora-474614.firebaseapp.com',
    storageBucket: 'findora-474614.firebasestorage.app',
    measurementId: 'G-MBDLK7YTS8',
  );
}
